import React, { useEffect, useState } from 'react';
import type { DesignerMoodboardSummary, DesignerProfile, DesignerSocialStats, MoodBoard } from '../types';
import { getMoodboardCoverImage, moodboardMaterialCount } from '../utils/moodboardFeedUtils';
import { isAutoGeneratedUsername } from '../utils/profileDisplayName';
import { getDesignerProfile } from '../services/designerProfileService';
import { updateDesignerProfile } from '../services/profileService';
import { getCollectedMoodboards } from '../services/collectedMoodboardService';
import AvatarUpload from './AvatarUpload';
import type { Material } from '../types';

type TabKey = 'boards' | 'collections';

interface DesignerPageProps {
  mode: 'owner' | 'public';
  designerId: string;
  viewerId?: string;
  materials: Material[];
  ownedMoodboards?: MoodBoard[];
  onSelectMoodboard: (board: MoodBoard) => void;
  onBack: () => void;
  onProfileUpdated?: (patch: { company?: string | null }) => void;
}

function toSummary(board: MoodBoard, materials: Material[]): DesignerMoodboardSummary {
  return {
    id: board.id,
    name: board.name,
    coverImage: getMoodboardCoverImage(board, materials),
    materialCount: moodboardMaterialCount(board),
    publishedAt: board.publishedAt,
  };
}

function resolveDisplayName(company: string | null | undefined, username: string | null | undefined): string {
  const c = company?.trim();
  if (c) return c;
  const u = username?.trim();
  if (u && !isAutoGeneratedUsername(u)) return u;
  return '';
}

const EditIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
  </svg>
);

function ProfileSocialStats({ stats }: { stats: DesignerSocialStats }) {
  return (
    <div className="flex items-center gap-6 md:gap-8">
      <div>
        <p className="text-sm font-black tabular-nums leading-none">{stats.followersCount}</p>
        <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mt-1">Followers</p>
      </div>
      <div>
        <p className="text-sm font-black tabular-nums leading-none">{stats.followingCount}</p>
        <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mt-1">Following</p>
      </div>
      <div>
        <p className="text-sm font-black tabular-nums leading-none">{stats.moodboardFavoritesCount}</p>
        <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mt-1">Collections</p>
      </div>
    </div>
  );
}

const DesignerPage: React.FC<DesignerPageProps> = ({
  mode,
  designerId,
  viewerId,
  materials,
  ownedMoodboards = [],
  onSelectMoodboard,
  onBack,
  onProfileUpdated,
}) => {
  const [profile, setProfile] = useState<DesignerProfile | null>(null);
  const [publicBoards, setPublicBoards] = useState<MoodBoard[]>([]);
  const [collected, setCollected] = useState<MoodBoard[]>([]);
  const [tab, setTab] = useState<TabKey>('boards');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editUsername, setEditUsername] = useState('');
  const [editBio, setEditBio] = useState('');
  const [editAvatar, setEditAvatar] = useState('');
  const [toast, setToast] = useState<string | null>(null);

  const showToast = (message: string) => {
    setToast(message);
    window.setTimeout(() => setToast((t) => (t === message ? null : t)), 3200);
  };

  const handleAvatarChange = async (url: string) => {
    setEditAvatar(url);
    const result = await updateDesignerProfile(designerId, { avatar: url });
    if (!result.ok) {
      showToast(result.error);
      return;
    }
    setProfile((prev) => (prev ? { ...prev, avatar: url } : prev));
  };

  const isOwner = mode === 'owner' && viewerId === designerId;

  useEffect(() => {
    let cancelled = false;
    setLoading(true);

    void (async () => {
      if (isOwner) {
        const p = await getDesignerProfile(designerId);
        const cols = await getCollectedMoodboards(designerId);
        if (!cancelled) {
          setProfile(p);
          setPublicBoards(p?.boards ?? []);
          setCollected(cols);
          setEditUsername(resolveDisplayName(p?.company, p?.username));
          setEditBio(p?.bio ?? '');
          setEditAvatar(p?.avatar ?? '');
          setLoading(false);
        }
      } else {
        const p = await getDesignerProfile(designerId);
        if (!cancelled) {
          setProfile(p);
          setPublicBoards(p?.boards ?? []);
          setLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [designerId, isOwner]);

  const ownedSummaries = ownedMoodboards.map((b) => toSummary(b, materials));
  const displayBoards =
    isOwner && tab === 'collections'
      ? collected.map((b) => toSummary(b, materials))
      : isOwner
        ? ownedSummaries
        : (profile?.publicMoodboards ?? []);

  const handleSaveProfile = async () => {
    if (!isOwner) return;
    setSaving(true);
    const name = editUsername.trim();
    const result = await updateDesignerProfile(designerId, {
      company: name || null,
      username: name || undefined,
      bio: editBio.trim() || null,
      avatar: editAvatar.trim() || null,
    });
    setSaving(false);
    if (!result.ok) {
      showToast(result.error);
      return;
    }
    setProfile((prev) =>
      prev
        ? {
            ...prev,
            company: name || null,
            username: name || prev.username,
            bio: editBio.trim() || null,
            avatar: editAvatar.trim() || null,
          }
        : prev
    );
    setIsEditing(false);
    showToast('资料已保存');
    onProfileUpdated?.({ company: name || null });
  };

  const startEditing = () => {
    setEditUsername(resolveDisplayName(profile?.company, profile?.username));
    setEditBio(profile?.bio ?? '');
    setIsEditing(true);
  };

  if (loading) {
    return <p className="text-sm text-gray-400 font-bold py-20 text-center">加载中…</p>;
  }

  if (!profile && !isOwner) {
    return (
      <div className="max-w-3xl mx-auto py-20 text-center">
        <p className="text-gray-400 font-bold">未找到该设计师</p>
        <button type="button" onClick={onBack} className="mt-4 text-sm font-bold text-black">
          返回
        </button>
      </div>
    );
  }

  const avatar = isOwner ? editAvatar || profile?.avatar : profile?.avatar;
  const displayName = resolveDisplayName(profile?.company, profile?.username);
  const publicDisplayName = displayName || '设计师';

  return (
    <div className="max-w-5xl mx-auto pb-16 relative">
      {toast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[300] px-5 py-3 bg-black text-white text-xs font-bold rounded-2xl shadow-xl max-w-[90vw] text-center">
          {toast}
        </div>
      )}
      <button
        type="button"
        onClick={onBack}
        className="mb-6 text-sm font-bold text-gray-500 hover:text-black transition-colors"
      >
        ← 返回探索库
      </button>

      <div className="mb-10">
        {isOwner ? (
          <>
            <AvatarUpload
              avatarUrl={editAvatar || profile?.avatar || null}
              onAvatarChange={(url) => void handleAvatarChange(url)}
              onToast={showToast}
            />

            {profile?.stats && (
              <div className="mt-4 mb-1">
                <ProfileSocialStats stats={profile.stats} />
              </div>
            )}

            {!isEditing ? (
              <div className="mt-4 max-w-xl">
                <div className="flex items-start gap-2">
                  <div className="min-w-0 flex-1">
                    <p className="text-lg md:text-xl font-black uppercase tracking-wide leading-tight">
                      {displayName || '未设置名称'}
                    </p>
                    {profile?.bio ? (
                      <p className="text-sm text-gray-600 leading-snug mt-1.5">{profile.bio}</p>
                    ) : (
                      <p className="text-sm text-gray-300 mt-1.5">暂无简介</p>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={startEditing}
                    className="shrink-0 p-2 rounded-full text-gray-400 hover:text-black hover:bg-gray-100 transition-colors"
                    title="编辑资料"
                    aria-label="编辑资料"
                  >
                    <EditIcon />
                  </button>
                </div>
              </div>
            ) : (
              <div className="mt-4 max-w-xl space-y-2.5">
                <input
                  type="text"
                  value={editUsername}
                  onChange={(e) => setEditUsername(e.target.value)}
                  placeholder="工作室 / 展示名称"
                  className="w-full text-sm p-2.5 rounded-xl bg-gray-50 border-none outline-none focus:ring-1 focus:ring-black font-bold uppercase tracking-wide"
                />
                <textarea
                  value={editBio}
                  onChange={(e) => setEditBio(e.target.value.slice(0, 100))}
                  placeholder="个人简介（最多 100 字）"
                  rows={3}
                  className="w-full text-sm p-3 rounded-xl bg-gray-50 border-none outline-none focus:ring-1 focus:ring-black resize-none leading-snug"
                />
                <div className="flex items-center justify-between gap-4 pt-1">
                  <span className="text-[10px] text-gray-400 font-bold">{editBio.length}/100</span>
                  <button
                    type="button"
                    disabled={saving}
                    onClick={() => void handleSaveProfile()}
                    className="px-5 py-2 bg-black text-white rounded-xl text-xs font-bold disabled:opacity-50"
                  >
                    {saving ? '保存中…' : '保存资料'}
                  </button>
                </div>
              </div>
            )}
          </>
        ) : (
          <div className="flex flex-col sm:flex-row gap-6">
            <div className="shrink-0">
              {avatar ? (
                <img
                  src={avatar}
                  alt=""
                  className="w-24 h-24 md:w-28 md:h-28 rounded-full object-cover border border-gray-100 shadow-sm"
                />
              ) : (
                <div className="w-24 h-24 md:w-28 md:h-28 rounded-full bg-gray-100 flex items-center justify-center text-3xl text-gray-300">
                  👤
                </div>
              )}
              {profile?.stats && (
                <div className="mt-4">
                  <ProfileSocialStats stats={profile.stats} />
                </div>
              )}
            </div>
            <div className="min-w-0 pt-1">
              <p className="text-lg md:text-xl font-black uppercase tracking-wide leading-tight">
                {publicDisplayName}
              </p>
              {profile?.bio && (
                <p className="text-sm text-gray-600 leading-snug mt-1.5 max-w-xl">{profile.bio}</p>
              )}
            </div>
          </div>
        )}
      </div>

      {isOwner && (
        <div className="flex gap-2 mb-6">
          <button
            type="button"
            onClick={() => setTab('boards')}
            className={`px-4 py-2 rounded-full text-xs font-bold transition-colors ${
              tab === 'boards' ? 'bg-black text-white' : 'bg-gray-100 text-gray-500'
            }`}
          >
            我的情绪板
          </button>
          <button
            type="button"
            onClick={() => setTab('collections')}
            className={`px-4 py-2 rounded-full text-xs font-bold transition-colors ${
              tab === 'collections' ? 'bg-black text-white' : 'bg-gray-100 text-gray-500'
            }`}
          >
            我的收藏
          </button>
        </div>
      )}

      <div className={`grid grid-cols-2 md:grid-cols-3 gap-5 ${isOwner ? '' : 'mt-2'}`}>
        {displayBoards.map((summary) => {
          const board =
            isOwner && tab === 'collections'
              ? collected.find((b) => b.id === summary.id)
              : isOwner
                ? ownedMoodboards.find((b) => b.id === summary.id)
                : publicBoards.find((b) => b.id === summary.id);
          const fallbackBoard: MoodBoard = board ?? {
            id: summary.id,
            name: summary.name,
            items: [],
            isPaid: false,
            maxMaterials: 10,
            publishedAt: summary.publishedAt,
            isPublished: true,
            visibility: 'public',
          };

          return (
            <button
              key={summary.id}
              type="button"
              onClick={() => {
                const enriched =
                  !isOwner && profile
                    ? {
                        ...fallbackBoard,
                        ownerId: designerId,
                        ownerName: publicDisplayName,
                        ownerAvatar: profile.avatar,
                      }
                    : fallbackBoard;
                onSelectMoodboard(enriched);
              }}
              className="text-left bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-lg transition-all overflow-hidden group"
            >
              <div className="aspect-[4/3] bg-gray-100 overflow-hidden">
                {summary.coverImage ? (
                  <img
                    src={summary.coverImage}
                    alt=""
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center text-3xl text-gray-300">
                    🎨
                  </div>
                )}
              </div>
              <div className="p-4">
                <h3 className="font-bold text-sm truncate">{summary.name}</h3>
                <p className="text-[10px] text-gray-400 font-bold mt-1 uppercase tracking-wider">
                  {summary.materialCount} 款材料
                </p>
              </div>
            </button>
          );
        })}
        {displayBoards.length === 0 && (
          <p className="col-span-full text-center text-gray-300 text-sm py-16">暂无内容</p>
        )}
      </div>
    </div>
  );
};

export default DesignerPage;
