import React, { useEffect, useState } from 'react';
import type { Material, SupplierProfile } from '../types';
import { isAutoGeneratedUsername } from '../utils/profileDisplayName';
import { getSupplierProfile } from '../services/supplierProfileService';
import { updateDesignerProfile } from '../services/profileService';
import { resolveProfileAvatarUrl } from '../services/assetReadUrlService';
import AvatarUpload from './AvatarUpload';
import { pickLocale } from '../utils/localizedText';

interface SupplierPageProps {
  mode: 'owner' | 'public';
  supplierId: string;
  viewerId?: string;
  materials: Material[];
  onSelectMaterial: (material: Material) => void;
  onBack: () => void;
  onProfileUpdated?: (patch: { company?: string | null; avatar?: string | null }) => void;
}

function resolveDisplayName(company: string | null | undefined, username: string | null | undefined): string {
  const c = company?.trim();
  if (c) return c;
  const u = username?.trim();
  if (u && !isAutoGeneratedUsername(u)) return u;
  return '';
}

const EditIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
  </svg>
);

const SupplierPage: React.FC<SupplierPageProps> = ({
  mode,
  supplierId,
  viewerId,
  materials,
  onSelectMaterial,
  onBack,
  onProfileUpdated,
}) => {
  const isOwner = mode === 'owner' && viewerId === supplierId;
  const [profile, setProfile] = useState<SupplierProfile | null>(null);
  const [loading, setLoading] = useState(!isOwner);
  const [saving, setSaving] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editUsername, setEditUsername] = useState('');
  const [editBio, setEditBio] = useState('');
  const [editAvatar, setEditAvatar] = useState('');
  const [toast, setToast] = useState<string | null>(null);

  const showToast = (message: string) => {
    setToast(message);
    window.setTimeout(() => setToast((t) => (t === message ? null : t)), 3200);
  };

  const handleAvatarChange = async (stored: string) => {
    const result = await updateDesignerProfile(supplierId, { avatar: stored });
    if (result.ok === false) {
      showToast(result.error);
      return;
    }
    const display = (await resolveProfileAvatarUrl(stored)) || stored;
    setEditAvatar(display);
    setProfile((prev) => (prev ? { ...prev, avatar: display } : prev));
    onProfileUpdated?.({ avatar: display });
  };

  useEffect(() => {
    let cancelled = false;

    if (isOwner) {
      setLoading(false);
    } else {
      setLoading(true);
    }

    const loadTimeout = window.setTimeout(() => {
      if (!cancelled) setLoading(false);
    }, 10000);

    void (async () => {
      try {
        const p = await getSupplierProfile(supplierId);
        if (cancelled) return;
        setProfile(p);
        setEditUsername(resolveDisplayName(p?.company, p?.username));
        setEditBio(p?.bio ?? '');
        setEditAvatar(p?.avatar ?? '');
      } catch (err) {
        console.error('[SupplierPage] load failed:', err);
      } finally {
        if (!cancelled) setLoading(false);
        window.clearTimeout(loadTimeout);
      }
    })();

    return () => {
      cancelled = true;
      window.clearTimeout(loadTimeout);
    };
  }, [supplierId, isOwner]);

  const handleSaveProfile = async () => {
    if (!isOwner) return;
    setSaving(true);
    const name = editUsername.trim();
    const result = await updateDesignerProfile(supplierId, {
      company: name || null,
      username: name || undefined,
      bio: editBio.trim() || null,
      avatar: editAvatar.trim() || null,
    });
    setSaving(false);
    if (result.ok === false) {
      showToast(result.error);
      return;
    }
    setProfile((prev) =>
      prev
        ? {
            ...prev,
            company: name || null,
            username: name || prev.username,
            bio: editBio.trim() || null,
            avatar: editAvatar.trim() || null,
          }
        : prev
    );
    setIsEditing(false);
    showToast('资料已保存');
    const avatarDisplay =
      (await resolveProfileAvatarUrl(editAvatar.trim() || null)) || editAvatar.trim() || null;
    if (avatarDisplay) setEditAvatar(avatarDisplay);
    onProfileUpdated?.({ company: name || null, avatar: avatarDisplay });
  };

  const startEditing = () => {
    setEditUsername(resolveDisplayName(profile?.company, profile?.username));
    setEditBio(profile?.bio ?? '');
    setIsEditing(true);
  };

  const cancelEditing = () => {
    setEditUsername(resolveDisplayName(profile?.company, profile?.username));
    setEditBio(profile?.bio ?? '');
    setIsEditing(false);
  };

  if (loading) {
    return <p className="text-sm text-gray-400 font-bold py-20 text-center">加载中…</p>;
  }

  if (!profile && !isOwner) {
    return (
      <div className="max-w-3xl mx-auto py-20 text-center">
        <p className="text-gray-400 font-bold">未找到该材料商</p>
        <button type="button" onClick={onBack} className="mt-4 text-sm font-bold text-black">
          返回
        </button>
      </div>
    );
  }

  const avatar = isOwner ? editAvatar || profile?.avatar : profile?.avatar;
  const displayName = resolveDisplayName(profile?.company, profile?.username);
  const publicDisplayName = displayName || '材料商';
  const listed = materials.filter((m) => m.supplierId === supplierId);

  return (
    <div className="max-w-5xl mx-auto pb-16 relative">
      {toast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[300] px-5 py-3 bg-black text-white text-xs font-bold rounded-2xl shadow-xl max-w-[90vw] text-center">
          {toast}
        </div>
      )}
      <button
        type="button"
        onClick={onBack}
        className="mb-6 text-sm font-bold text-gray-500 hover:text-black transition-colors"
      >
        ← 返回探索库
      </button>

      <div className="mb-10">
        {isOwner ? (
          <>
            <AvatarUpload
              avatarUrl={editAvatar || profile?.avatar || null}
              onAvatarChange={(url) => void handleAvatarChange(url)}
              onToast={showToast}
            />

            {!isEditing ? (
              <div className="mt-4 max-w-xl">
                <div className="flex items-start gap-2">
                  <div className="min-w-0 flex-1">
                    <p className="text-lg md:text-xl font-black uppercase tracking-wide leading-tight">
                      {displayName || '未设置名称'}
                    </p>
                    {profile?.bio ? (
                      <p className="text-sm text-gray-600 leading-snug mt-1.5">{profile.bio}</p>
                    ) : (
                      <p className="text-sm text-gray-300 mt-1.5">暂无简介</p>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={startEditing}
                    className="shrink-0 p-2 rounded-full text-gray-400 hover:text-black hover:bg-gray-100 transition-colors"
                    title="编辑资料"
                    aria-label="编辑资料"
                  >
                    <EditIcon />
                  </button>
                </div>
              </div>
            ) : (
              <div className="mt-4 max-w-xl space-y-2.5">
                <input
                  type="text"
                  value={editUsername}
                  onChange={(e) => setEditUsername(e.target.value)}
                  placeholder="品牌 / 展示名称"
                  className="w-full text-sm p-2.5 rounded-xl bg-gray-50 border-none outline-none focus:ring-1 focus:ring-black font-bold uppercase tracking-wide"
                />
                <textarea
                  value={editBio}
                  onChange={(e) => setEditBio(e.target.value.slice(0, 100))}
                  placeholder="简介（最多 100 字）"
                  rows={3}
                  className="w-full text-sm p-3 rounded-xl bg-gray-50 border-none outline-none focus:ring-1 focus:ring-black resize-none leading-snug"
                />
                <div className="flex items-center justify-between gap-4 pt-1">
                  <span className="text-[10px] text-gray-400 font-bold">{editBio.length}/100</span>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      disabled={saving}
                      onClick={cancelEditing}
                      className="px-5 py-2 bg-gray-100 text-gray-700 rounded-xl text-xs font-bold disabled:opacity-50"
                    >
                      取消
                    </button>
                    <button
                      type="button"
                      disabled={saving}
                      onClick={() => void handleSaveProfile()}
                      className="px-5 py-2 bg-black text-white rounded-xl text-xs font-bold disabled:opacity-50"
                    >
                      {saving ? '保存中…' : '保存'}
                    </button>
                  </div>
                </div>
              </div>
            )}
          </>
        ) : (
          <div className="flex flex-col sm:flex-row gap-6">
            <div className="shrink-0">
              {avatar ? (
                <img
                  src={avatar}
                  alt=""
                  className="w-24 h-24 md:w-28 md:h-28 rounded-full object-cover border border-gray-100 shadow-sm"
                />
              ) : (
                <div className="w-24 h-24 md:w-28 md:h-28 rounded-full bg-gray-100 flex items-center justify-center text-3xl text-gray-300">
                  👤
                </div>
              )}
            </div>
            <div className="min-w-0 pt-1">
              <p className="text-lg md:text-xl font-black uppercase tracking-wide leading-tight">
                {publicDisplayName}
              </p>
              {profile?.bio && (
                <p className="text-sm text-gray-600 leading-snug mt-1.5 max-w-xl">{profile.bio}</p>
              )}
            </div>
          </div>
        )}
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-5 mt-2">
        {listed.map((material) => (
          <button
            key={material.id}
            type="button"
            onClick={() => onSelectMaterial(material)}
            className="text-left bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-lg transition-all overflow-hidden group"
          >
            <div className="aspect-[4/3] bg-gray-100 overflow-hidden">
              {material.image ? (
                <img
                  src={material.image}
                  alt=""
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-3xl text-gray-300">
                  🧱
                </div>
              )}
            </div>
            <div className="p-4">
              <h3 className="font-bold text-sm truncate">{pickLocale(material.name)}</h3>
              <p className="text-[10px] text-gray-400 font-bold mt-1 uppercase tracking-wider">
                {material.category}
              </p>
            </div>
          </button>
        ))}
        {listed.length === 0 && (
          <p className="col-span-full text-center text-gray-300 text-sm py-16">暂无上架材料</p>
        )}
      </div>
    </div>
  );
};

export default SupplierPage;
