/** 导航栏 / 全局展示名：优先工作室名称，否则邮箱前缀 */
export function emailPrefix(email: string): string {
  return email.split('@')[0]?.trim() || '用户';
}

export function resolveUserDisplayName(input: {
  company?: string | null;
  email: string;
}): string {
  const company = input.company?.trim();
  if (company) return company;
  return emailPrefix(input.email);
}

/** 注册时自动生成的 username（email前缀_id片段），不在前台展示 */
export function isAutoGeneratedUsername(value: string): boolean {
  return /^\d+_[a-f0-9]{4,}$/i.test(value.trim());
}

/** 设计师公开展示名：company → 自定义 username → 邮箱前缀 */
export function resolveDesignerDisplayName(input: {
  company?: string | null;
  username?: string | null;
  email?: string | null;
}): string {
  const company = input.company?.trim();
  if (company) return company;
  const username = input.username?.trim();
  if (username && !isAutoGeneratedUsername(username)) return username;
  if (input.email?.trim()) return emailPrefix(input.email);
  return '设计师';
}

export function defaultDesignerAvatarUrl(userId: string): string {
  return `https://api.dicebear.com/7.x/avataaars/svg?seed=${userId}`;
}
